### ISSUE TITLE
CommonUtil没提供

### ISSUE THREAD

**Issue by marinLiu** [crazyqiang/AndroidStudy#1]
CommonUtil.measureWidthAndHeight方法，具体实现是什么呢？我想试试你的idea，谢谢

**Comment by crazyqiang** [comment]
public static void measureWidthAndHeight(View view) {
        int w = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED);
        int h = View.MeasureSpec.makeMeasureSpec(0, View.MeasureSpec.UNSPECIFIED);
        view.measure(w, h);
    }
其实就是测量模式设置成MeasureSpec.UNSPECIFIED，子View的测量就不用被约束了，但测试的时候有个问题，文章中也提到了，就是View的宽和高必须有一个是已知的具体值，才能正确测量出另一个，否则测量出来不太对，如有更好实现还望不吝赐教

**Comment by FengLinZhang** [comment]
厉害了 老铁

**Comment by ihtvr** [comment]
Fragment 设置背景报错 无法转化Activity,背景颜色是否可以选择从标记View以上或以下呢?

**Comment by AndroidAndYang** [comment]
在低版本下会报错
java.lang.NullPointerException
                                                                          at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:493)
                                                                          at android.view.View.measure(View.java:15612)
                                                                          at com.mayishuhui.airbook.utils.helper.CommonUtil.measureWidthAndHeight(CommonUtil.java:22)
                                                                          at com.mayishuhui.airbook.ui.component.popupwindow.CommonPopupWindow$Builder.create(CommonPopupWindow.java:148)
